lane :test do
  install_transporter
  configure_transporter(root_ca: "spec/fixtures/root_ca.pem")
  update_transporter_path

  UI.success("Transporter is now installed at: #{ENV['FASTLANE_ITUNES_TRANSPORTER_PATH']}")
end
